{{- range $relayer := .Values.relayers }}
{{- if eq $relayer.type "eth-relayer" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $relayer.type }}-{{ $relayer.name }}"
data:
  abi.json: |
    []
---
{{- end }}
{{- end }}
