{{- range $relayer := .Values.relayers }}
{{- if eq $relayer.type "eth-relayer" }}
{{ $defaultRelayer := get $.Values.defaultRelayers $relayer.type }}
{{ $initParams := dict "chains" $relayer.chains "port" $.Values.exposer.ports.rest "context" $ }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $relayer.type }}-{{ $relayer.name }}
spec:
  serviceName: {{ $relayer.type }}-{{ $relayer.name }}
  replicas: {{ $relayer.replicas }}
  podManagementPolicy: "Parallel"
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: relayer
      app.kubernetes.io/type: {{ $relayer.type }}
      app.kubernetes.io/name: {{ $relayer.type }}-{{ $relayer.name }}
  template:
    metadata:
      annotations:
        quality: release
        role: api-gateway
        sla: high
        tier: gateway
      labels:
        app.kubernetes.io/instance: relayer
        app.kubernetes.io/type: {{ $relayer.type }}
        app.kubernetes.io/name: {{ $relayer.type }}-{{ $relayer.name }}
        app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    spec:
      initContainers:
        - name: wait-for-eth
          image: {{ $relayer.image | default $defaultRelayer.image }}
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - sh
            - "-c"
            - |
              RLY_INDEX=${HOSTNAME##*-}
              echo "Relayer Index: $RLY_INDEX"

              apk add curl jq

              while true
              do
                epoch=$(curl -s http://prysm.$NAMESPACE.svc.cluster.local:3500/eth/v1/beacon/states/head/finality_checkpoints | jq -r '.data.finalized.epoch')
                echo "Finalized epoch: $epoch"

                if [ "$epoch" -gt 0 ]; then
                  break
                fi

                sleep 5
              done

              echo "Entered PoS stage"
        - name: deploy-contracts
          image: node:alpine
          imagePullPolicy: Always
          env:
            - name: KEYS_CONFIG
              value: /keys/keys.json
            - name: MNEMONIC
              valueFrom:
                secretKeyRef:
                  optional: true
                  name: eth-relayer
                  key: genesis
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - sh
            - "-c"
            - |
              RLY_INDEX=${HOSTNAME##*-}
              echo "Relayer Index: $RLY_INDEX"

              if [ -f /tmp/abi.json ]; then
                echo "The file /tmp/abi.json exists."
                exit 0;
              fi

              apk update
              apk add curl jq git bash tar

              if [ -z "$MNEMONIC" ]; then
                MNEMONIC=$(jq -r ".genesis[0].mnemonic" $KEYS_CONFIG)
              fi

              cd /tmp && rm -rf *
              cp /contracts/* .

              echo "Installing contract dependencies"
              npm -g install

              echo "Installing vibc-core-smart-contracts dependencies"
              npm i @open-ibc/vibc-core-smart-contracts tslib
              node node_modules/@open-ibc/vibc-core-smart-contracts/dist/index.js .

              echo "Deploying vibc smart contracts"
              ETH_ADDRESS=$(node address.js -m "$MNEMONIC" | jq -r ".ethereumAddress")
              echo "Ethereum address: $ETH_ADDRESS"

              echo "Balance before deployment"
              RPC=http://prysm.$NAMESPACE.svc.cluster.local:8545
              echo $(node balance.js -a $ETH_ADDRESS -r $RPC)

              node /tmp/deploy.js -m "$MNEMONIC" -c /tmp/IbcDispatcher.sol/IbcDispatcher.json -r $RPC
              node /tmp/deploy.js -m "$MNEMONIC" -c /tmp/IbcReceiver.sol/IbcReceiver.json -r $RPC
              node /tmp/deploy.js -m "$MNEMONIC" -c /tmp/IbcVerifier.sol/ZKMintVerifier.json -r $RPC

              VERIFIER_ADDRESS=$(node /tmp/deploy.js -m "$MNEMONIC" -c /tmp/Verifier.sol/Verifier.json -r $RPC)
              echo "Verifier address: $VERIFIER_ADDRESS"
              DISPATCHER_ADDRESS=$(node /tmp/deploy.js -m "$MNEMONIC" -c /tmp/Dispatcher.sol/Dispatcher.json \
              -r $RPC --args "$VERIFIER_ADDRESS,$ETH_ADDRESS,polyibc.Ethereum-Devnet." )
              echo "Dispatcher address: $DISPATCHER_ADDRESS"

              # create light client config files for polymer
              jq -n --arg addr "$DISPATCHER_ADDRESS" '{
              sc_address: $addr,
              abi_path: "/tmp/abi.json"
              }' > /tmp/altair.json
              jq '.abi' /tmp/Dispatcher.sol/Dispatcher.json > /tmp/abi.json
          workingDir: /tmp
          volumeMounts:
            - mountPath: /root
              name: relayer
            - mountPath: /keys
              name: keys
            - mountPath: /contracts
              name: contracts
            - name: shared
              mountPath: /tmp
          resources: {{- include "devnet.node.resources" ( dict "node" $relayer "context" $ ) | trim | nindent 12 }}
        - name: wait-for-polymer
          image: {{ $relayer.image | default $defaultRelayer.image }}
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - sh
            - "-c"
            - |
              RLY_INDEX=${HOSTNAME##*-}
              echo "Relayer Index: $RLY_INDEX"

              apk add curl jq

              while [ $(curl -sw '%{http_code}' http://polymer-genesis.$NAMESPACE.svc.cluster.local:8081/node_id -o /dev/null) -ne 200 ]; do
                echo "Genesis validator does not seem to be ready. Waiting for it to start..."
                sleep 10;
              done
              echo "Ready to start"

          volumeMounts:
            - mountPath: /root
              name: relayer
          resources: {{- include "devnet.node.resources" ( dict "node" $relayer "context" $ ) | trim | nindent 12 }}
        - name: vibc-init-relayer
          image: {{ $relayer.vibcImage | default $defaultRelayer.vibcImage }}
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KEYS_CONFIG
              value: /keys/keys.json
            - name: MNEMONIC
              valueFrom:
                secretKeyRef:
                  optional: true
                  name: vibc-relayer
                  key: relayer
          command:
            - sh
            - "-c"
            - |
              RLY_INDEX=${HOSTNAME##*-}
              echo "Relayer Index: $RLY_INDEX"

              apk add curl jq nodejs npm bash

              if [ -z "$MNEMONIC" ]; then
                MNEMONIC=$(jq -r ".relayers[0].mnemonic" $KEYS_CONFIG)
              fi

              cd /tmp
              cp /contracts/* .
              npm install

              echo "Adding chains"
              IBC_CORE_ADDRESS=$(jq -r '.sc_address' /tmp/altair.json)
              ABI=$(cat /tmp/abi.json)

              echo "Adding polymer chain"
              POLYMER_ADDRESS=$(node address.js -m "$MNEMONIC" -p polymer | jq -r ".cosmosAddress")
              echo "Polymer address: $POLYMER_ADDRESS"

              echo "Transfer tokens to address $POLYMER_ADDRESS"
              DENOM=token
              bash -e /scripts/transfer_tokens.sh $POLYMER_ADDRESS $DENOM http://polymer-genesis.$NAMESPACE.svc.cluster.local:8000/credit

              /vibc-relayer/vibc-relayer chains add --name polymer \
              --rpc-url http://polymer-genesis.$NAMESPACE.svc.cluster.local:26657 \
              --gas-price 0.0stake \
              --account "$POLYMER_ADDRESS" --key "$MNEMONIC" --type cosmos

              echo "Adding ethereum chain"
              ETH_ADDRESS=$(node address.js -m "$MNEMONIC" | jq -r ".ethereumAddress")
              ETH_PRIV_KEY=$(node address.js -m "$MNEMONIC" | jq -r ".ethereumPrivateKey")
              echo "Ethereum address: $ETH_ADDRESS"
              echo "Ethereum private key: $ETH_PRIV_KEY"

              /vibc-relayer/vibc-relayer chains add --name ethereum \
              --rpc-url http://prysm.$NAMESPACE.svc.cluster.local:8545 \
              --gas-price 0.0stake \
              --account "$ETH_ADDRESS" --key "$ETH_PRIV_KEY" --type evm \
              --contract-addr "$IBC_CORE_ADDRESS" \
              --contract-abi "$ABI"

              echo "Setting polling idle time"
              /vibc-relayer/vibc-relayer config set global.polling-idle-time 5000

              echo "Adding paths"
              /vibc-relayer/vibc-relayer paths add polymer ethereum polymer-ethereum
          volumeMounts:
            - name: shared
              mountPath: /tmp
            - mountPath: /root
              name: relayer
            - mountPath: /contracts
              name: contracts
            - mountPath: /keys
              name: keys
            - mountPath: /scripts
              name: scripts
          resources: {{- include "devnet.node.resources" ( dict "node" $relayer "context" $ ) | trim | nindent 12 }}
      containers:
        - name: vibc-relayer
          image: {{ $relayer.vibcImage | default $defaultRelayer.vibcImage }}
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - sh
            - "-c"
            - |
              RLY_INDEX=${HOSTNAME##*-}
              echo "Relayer Index: $RLY_INDEX"
              /vibc-relayer/vibc-relayer config set global.log-level verbose

              /vibc-relayer/vibc-relayer start
          resources: {{- include "devnet.node.resources" ( dict "node" $relayer "context" $ ) | trim | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          volumeMounts:
            - name: shared
              mountPath: /tmp
            - mountPath: /root
              name: relayer
        - name: eth-relayer
          image: {{ $relayer.image | default $defaultRelayer.image }}
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KEYS_CONFIG
              value: /keys/keys.json
            - name: MNEMONIC
              valueFrom:
                secretKeyRef:
                  optional: true
                  name: eth-relayer
                  key: relayer
          command:
            - sh
            - "-c"
            - |
              RLY_INDEX=${HOSTNAME##*-}
              echo "Relayer Index: $RLY_INDEX"

              apk add curl jq

              if [ -z "$MNEMONIC" ]; then
                MNEMONIC=$(jq -r ".relayers[0].mnemonic" $KEYS_CONFIG)
              fi

              PRYSM_IP=$(nslookup prysm.$NAMESPACE.svc.cluster.local | awk '/^Address: / { print $2 }')
              PRYSM_IP=$(echo "$PRYSM_IP" | xargs)

              POLYMER_IP=$(nslookup polymer-genesis.$NAMESPACE.svc.cluster.local | awk '/^Address: / { print $2 }')
              POLYMER_IP=$(echo "$POLYMER_IP" | xargs)

              IBC_CORE_ADDRESS=$(jq -r '.sc_address' /tmp/altair.json)

              # Make the curl request and store the JSON response in a variable
              response=$(curl -s "http://polymer-genesis.$NAMESPACE.svc.cluster.local:1317/polyibc/core/v1/clients/altair-0/client_state")
              CLIENT_STATE=$(echo "$response" | jq -r '.client_state')

              # Check if the "client_state" key exists in the JSON response
              if [ "$CLIENT_STATE" != "null" ]; then
                echo "Altair light client exists"
              else
                echo "Altair light client does not exist. Creating one..."

                /relayer/eth-relayer --consensus-host "http://prysm.$NAMESPACE.svc.cluster.local:3500" \
                --execution-host "http://prysm.$NAMESPACE.svc.cluster.local:8545" \
                --ibc-core-address "$IBC_CORE_ADDRESS" \
                --ibc-core-abi /tmp/abi.json \
                --router-host "http://polymer-genesis.$NAMESPACE.svc.cluster.local:9090" \
                --polymer-rpc-addr "http://polymer-genesis.$NAMESPACE.svc.cluster.local:26657" \
                --polymer-account-mnemonic "$MNEMONIC" \
                --local-dev-net --create-client-mode
              fi

              /relayer/eth-relayer --consensus-host "http://prysm.$NAMESPACE.svc.cluster.local:3500" \
              --execution-host "http://prysm.$NAMESPACE.svc.cluster.local:8545" \
              --ibc-core-address "$IBC_CORE_ADDRESS" \
              --ibc-core-abi /tmp/abi.json \
              --router-host "http://polymer-genesis.$NAMESPACE.svc.cluster.local:9090" \
              --polymer-rpc-addr "http://$POLYMER_IP:26657" \
              --polymer-account-mnemonic "$MNEMONIC" \
              --local-dev-net

          resources: {{- include "devnet.node.resources" ( dict "node" $relayer "context" $ ) | trim | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          volumeMounts:
            - name: shared
              mountPath: /tmp
            - mountPath: /root
              name: relayer
            - mountPath: /keys
              name: keys
      volumes:
        - name: relayer
          emptyDir: { }
        - name: keys
          configMap:
            name: keys
        - name: scripts
          configMap:
            name: setup-scripts
        - name: contracts
          configMap:
            name: contracts
        - name: shared
          persistentVolumeClaim:
            claimName: shared

---
{{- end }}
{{- end }}
