{{- range $relayer := .Values.relayers }}
{{- if eq $relayer.type "eth-relayer" }}
{{ $defaultRelayer := get $.Values.defaultRelayers $relayer.type }}
{{ $initParams := dict "chains" $relayer.chains "port" $.Values.exposer.ports.rest "context" $ }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $relayer.type }}-{{ $relayer.name }}
spec:
  serviceName: {{ $relayer.type }}-{{ $relayer.name }}
  replicas: {{ $relayer.replicas }}
  podManagementPolicy: "Parallel"
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: relayer
      app.kubernetes.io/type: {{ $relayer.type }}
      app.kubernetes.io/name: {{ $relayer.type }}-{{ $relayer.name }}
  template:
    metadata:
      annotations:
        quality: release
        role: api-gateway
        sla: high
        tier: gateway
      labels:
        app.kubernetes.io/instance: relayer
        app.kubernetes.io/type: {{ $relayer.type }}
        app.kubernetes.io/name: {{ $relayer.type }}-{{ $relayer.name }}
        app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    spec:
      initContainers:
        - name: wait-for-eth
          image: {{ $relayer.image | default $defaultRelayer.image }}
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - sh
            - "-c"
            - |
              RLY_INDEX=${HOSTNAME##*-}
              echo "Relayer Index: $RLY_INDEX"

              apk add curl jq

              while true
              do
                epoch=$(curl -s http://prysm.$NAMESPACE.svc.cluster.local:3500/eth/v1/beacon/states/head/finality_checkpoints | jq -r '.data.finalized.epoch')
                echo "Finalized epoch: $epoch"

                if [ "$epoch" -gt 0 ]; then
                  break
                fi

                sleep 5
              done

              echo "Entered PoS stage"
        - name: deploy-contracts
          image: {{ $relayer.image | default $defaultRelayer.image }}
          imagePullPolicy: Always
          env:
            - name: KEYS_CONFIG
              value: /keys/keys.json
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - sh
            - "-c"
            - |
              RLY_INDEX=${HOSTNAME##*-}
              echo "Relayer Index: $RLY_INDEX"

              apk add curl jq nodejs npm
              MNEMONIC=$(jq -r ".genesis[0].mnemonic" $KEYS_CONFIG)

              cd /tmp
              cp /contracts/* .
              npm install

              # deploy vibc smart contracts
              VERIFIER_ADDRESS=$(node deploy.js -m "$MNEMONIC" -c Verifier.json -r "http://prysm.$NAMESPACE.svc.cluster.local:8545")
              echo "Verifier address: $VERIFIER_ADDRESS"
              DISPATCHER_ADDRESS=$(node deploy.js -m "$MNEMONIC" -c Dispatcher.json -r "http://prysm.$NAMESPACE.svc.cluster.local:8545" --args "$VERIFIER_ADDRESS")
              echo "Dispatcher address: $DISPATCHER_ADDRESS"

              # create light client config files for polymer
              jq -n --arg addr "$DISPATCHER_ADDRESS" '{
              sc_address: $addr,
              abi_path: "/tmp/abi.json"
              }' > altair.json
              jq '.abi' Dispatcher.json > abi.json
          workingDir: /tmp
          volumeMounts:
            - mountPath: /root
              name: relayer
            - mountPath: /keys
              name: keys
            - mountPath: /contracts
              name: contracts
            - name: shared
              mountPath: /tmp
          resources: {{- include "devnet.node.resources" ( dict "node" $relayer "context" $ ) | trim | nindent 12 }}
        - name: wait-for-polymer
          image: {{ $relayer.image | default $defaultRelayer.image }}
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - sh
            - "-c"
            - |
              RLY_INDEX=${HOSTNAME##*-}
              echo "Relayer Index: $RLY_INDEX"

              apk add curl jq

              while [ $(curl -sw '%{http_code}' http://polymer-genesis.$NAMESPACE.svc.cluster.local:8081/node_id -o /dev/null) -ne 200 ]; do
                echo "Genesis validator does not seem to be ready. Waiting for it to start..."
                sleep 10;
              done
              echo "Ready to start"

          volumeMounts:
            - mountPath: /root
              name: relayer
            - mountPath: /configs
              name: relayer-config
          resources: {{- include "devnet.node.resources" ( dict "node" $relayer "context" $ ) | trim | nindent 12 }}
        - name: vibc-init-relayer
          image: {{ $relayer.vibcImage | default $defaultRelayer.vibcImage }}
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KEYS_CONFIG
              value: /keys/keys.json
          command:
            - sh
            - "-c"
            - |
              RLY_INDEX=${HOSTNAME##*-}
              echo "Relayer Index: $RLY_INDEX"

              apk add curl jq

              echo "Adding chains"
              MNEMONIC=$(jq -r ".genesis[0].mnemonic" $KEYS_CONFIG)
              IBC_CORE_ADDRESS=$(jq -r '.sc_address' /tmp/altair.json)
              ABI=$(cat /tmp/abi.json)

              echo "Adding polymer chain"

              /vibc-relayer/vibc-relayer chains add --name polymer \
              --rpc-url http://polymer-genesis.$NAMESPACE.svc.cluster.local:26657 \
              --gas-price 0.0stake \
              --account "polymerase1ys2ez49cgnwyz8wgsem3wam7zfkz6302475jqz" --key "$MNEMONIC" --type cosmos

              echo "Adding ethereum chain"

              /vibc-relayer/vibc-relayer chains add --name ethereum \
              --rpc-url http://prysm.$NAMESPACE.svc.cluster.local:8545 \
              --gas-price 0.0stake \
              --account "0x2C8454f3A88070ced57E5B39762E6d983aC718B9" --key "0x408890c2b5eba1664bbd33ced41ec0d1322c48b2f65934142e0d8855b552204c" --type evm \
              --contract-addr "$IBC_CORE_ADDRESS" \
              --contract-abi "$ABI"

              echo "Setting polling idle time"
              /vibc-relayer/vibc-relayer config set global.polling-idle-time 5000

              echo "Adding paths"
              /vibc-relayer/vibc-relayer paths add polymer ethereum polymer-ethereum

              /vibc-relayer/vibc-relayer config show
          volumeMounts:
            - name: shared
              mountPath: /tmp
            - mountPath: /root
              name: relayer
            - mountPath: /keys
              name: keys
            - mountPath: /configs
              name: relayer-config
          resources: {{- include "devnet.node.resources" ( dict "node" $relayer "context" $ ) | trim | nindent 12 }}
      containers:
        - name: vibc-relayer
          image: {{ $relayer.vibcImage | default $defaultRelayer.vibcImage }}
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - sh
            - "-c"
            - |
              RLY_INDEX=${HOSTNAME##*-}
              echo "Relayer Index: $RLY_INDEX"
              /vibc-relayer/vibc-relayer config set global.log-level verbose

              /vibc-relayer/vibc-relayer start
          resources: {{- include "devnet.node.resources" ( dict "node" $relayer "context" $ ) | trim | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          volumeMounts:
            - name: shared
              mountPath: /tmp
            - mountPath: /root
              name: relayer
            - mountPath: /configs
              name: relayer-config
        - name: eth-relayer
          image: {{ $relayer.image | default $defaultRelayer.image }}
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KEYS_CONFIG
              value: /keys/keys.json
          command:
            - sh
            - "-c"
            - |
              RLY_INDEX=${HOSTNAME##*-}
              echo "Relayer Index: $RLY_INDEX"

              apk add curl jq

              MNEMONIC=$(jq -r ".genesis[0].mnemonic" $KEYS_CONFIG)

              PRYSM_IP=$(nslookup prysm.$NAMESPACE.svc.cluster.local | awk '/^Address: / { print $2 }')
              PRYSM_IP=$(echo "$PRYSM_IP" | xargs)

              POLYMER_IP=$(nslookup polymer-genesis.$NAMESPACE.svc.cluster.local | awk '/^Address: / { print $2 }')
              POLYMER_IP=$(echo "$POLYMER_IP" | xargs)

              IBC_CORE_ADDRESS=$(jq -r '.sc_address' /tmp/altair.json)

              # Make the curl request and store the JSON response in a variable
              response=$(curl -s "http://polymer-genesis.$NAMESPACE.svc.cluster.local:1317/polyibc/core/v1/clients/altair-0/client_state")
              CLIENT_STATE=$(echo "$response" | jq -r '.client_state')

              # Check if the "client_state" key exists in the JSON response
              if [ "$CLIENT_STATE" != "null" ]; then
                echo "Altair light client exists"
              else
                echo "Altair light client does not exist. Creating one..."

                /relayer/eth-relayer --consensus-host "http://prysm.$NAMESPACE.svc.cluster.local:3500" \
                --execution-host "http://prysm.$NAMESPACE.svc.cluster.local:8545" \
                --ibc-core-address "$IBC_CORE_ADDRESS" \
                --ibc-core-abi /tmp/abi.json \
                --router-host "http://polymer-genesis.$NAMESPACE.svc.cluster.local:9090" \
                --polymer-rpc-addr "http://polymer-genesis.$NAMESPACE.svc.cluster.local:26657" \
                --polymer-account-mnemonic "$MNEMONIC" \
                --local-dev-net --create-client-mode
              fi

              /relayer/eth-relayer --consensus-host "http://prysm.$NAMESPACE.svc.cluster.local:3500" \
              --execution-host "http://prysm.$NAMESPACE.svc.cluster.local:8545" \
              --ibc-core-address "$IBC_CORE_ADDRESS" \
              --ibc-core-abi /configs/abi.json \
              --router-host "http://polymer-genesis.$NAMESPACE.svc.cluster.local:9090" \
              --polymer-rpc-addr "http://$POLYMER_IP:26657" \
              --polymer-account-mnemonic "$MNEMONIC" \
              --local-dev-net

          resources: {{- include "devnet.node.resources" ( dict "node" $relayer "context" $ ) | trim | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          volumeMounts:
            - name: shared
              mountPath: /tmp
            - mountPath: /root
              name: relayer
            - mountPath: /keys
              name: keys
            - mountPath: /configs
              name: relayer-config
      volumes:
        - name: relayer
          emptyDir: { }
        - name: keys
          configMap:
            name: keys
        - name: contracts
          configMap:
            name: contracts
        - name: shared
          persistentVolumeClaim:
            claimName: shared
        - name: relayer-config
          configMap:
            name: "{{ $relayer.type }}-{{ $relayer.name }}"

---
{{- end }}
{{- end }}
