{{- range $relayer := .Values.relayers }}
{{- if eq $relayer.type "eth-relayer" }}
{{ $defaultRelayer := get $.Values.defaultRelayers $relayer.type }}
{{ $initParams := dict "chains" $relayer.chains "port" $.Values.exposer.ports.rest "context" $ }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $relayer.type }}-{{ $relayer.name }}
spec:
  serviceName: {{ $relayer.type }}-{{ $relayer.name }}
  replicas: {{ $relayer.replicas }}
  podManagementPolicy: "Parallel"
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: relayer
      app.kubernetes.io/type: {{ $relayer.type }}
      app.kubernetes.io/name: {{ $relayer.type }}-{{ $relayer.name }}
  template:
    metadata:
      annotations:
        quality: release
        role: api-gateway
        sla: high
        tier: gateway
      labels:
        app.kubernetes.io/instance: relayer
        app.kubernetes.io/type: {{ $relayer.type }}
        app.kubernetes.io/name: {{ $relayer.type }}-{{ $relayer.name }}
        app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    spec:
      initContainers:
        - name: wait-for-eth
          image: {{ $relayer.image | default $defaultRelayer.image }}
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - sh
            - "-c"
            - |
              set -e
              RLY_INDEX=${HOSTNAME##*-}
              echo "Relayer Index: $RLY_INDEX"

              apk add curl jq bash

              while true
              do
                epoch=$(curl -s http://prysm.$NAMESPACE.svc.cluster.local:3500/eth/v1/beacon/states/head/finality_checkpoints | jq -r '.data.finalized.epoch')
                echo "Finalized epoch: $epoch"

                if [ "$epoch" -gt 0 ]; then
                  break
                fi

                sleep 5
              done

              echo "Entered PoS stage"
        - name: deploy-contracts
          image: node:alpine
          imagePullPolicy: Always
          env:
            - name: KEYS_CONFIG
              value: /keys/keys.json
            - name: MNEMONIC
              valueFrom:
                secretKeyRef:
                  optional: true
                  name: eth-relayer
                  key: genesis
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - sh
            - "-c"
            - |
              set -e
              RLY_INDEX=${HOSTNAME##*-}
              RPC=http://prysm.$NAMESPACE.svc.cluster.local:8545
              echo "Relayer Index: $RLY_INDEX"
              echo "RPC: $RPC"

              apk update
              apk add curl jq git bash tar

              if [ -z "$MNEMONIC" ]; then
                MNEMONIC=$(jq -r ".genesis[0].mnemonic" $KEYS_CONFIG)
              fi

              DISPATCHER_ADDRESS="{{ $relayer.dispatcher }}"

              if [ -f /root/altair.json ]; then
                echo "Found altair config file"
                if [ $DISPATCHER_ADDRESS == $(jq -r ".sc_address" /root/altair.json) ]; then
                  exit 0;
                else
                  echo "Dispatcher address in altair config file does not match the one in values.yaml"
                fi
              fi

              echo "Installing vibc-core-smart-contracts dependencies"
              npm i @open-ibc/vibc-core-smart-contracts@0.0.11 tslib
              node node_modules/@open-ibc/vibc-core-smart-contracts/dist/index.js .

              # create light client config files for polymer
              jq -n --arg addr "$DISPATCHER_ADDRESS" '{
              sc_address: $addr,
              abi_path: "/root/abi.json"
              }' > /root/altair.json
              jq '.abi' /root/Dispatcher.sol/Dispatcher.json > /root/abi.json
          workingDir: /root
          volumeMounts:
            - mountPath: /root
              name: relayer
            - mountPath: /keys
              name: keys
            - mountPath: /contracts
              name: contracts
            - mountPath: /scripts
              name: scripts
          resources: {{- include "devnet.node.resources" ( dict "node" $relayer "context" $ ) | trim | nindent 12 }}
        - name: wait-for-polymer
          image: {{ $relayer.image | default $defaultRelayer.image }}
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - sh
            - "-c"
            - |
              set -e
              RLY_INDEX=${HOSTNAME##*-}
              echo "Relayer Index: $RLY_INDEX"

              apk add curl jq bash

              while [ $(curl -sw '%{http_code}' http://polymer-genesis.$NAMESPACE.svc.cluster.local:8081/node_id -o /dev/null) -ne 200 ]; do
                echo "Genesis validator does not seem to be ready. Waiting for it to start..."
                sleep 10;
              done
              echo "Ready to start"

          volumeMounts:
            - mountPath: /root
              name: relayer
          resources: {{- include "devnet.node.resources" ( dict "node" $relayer "context" $ ) | trim | nindent 12 }}
        - name: vibc-init-relayer
          image: {{ $relayer.vibcImage | default $defaultRelayer.vibcImage }}
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KEYS_CONFIG
              value: /keys/keys.json
            - name: MNEMONIC
              valueFrom:
                secretKeyRef:
                  optional: true
                  name: vibc-relayer
                  key: relayer
          command:
            - sh
            - "-c"
            - |
              set -e
              RLY_INDEX=${HOSTNAME##*-}
              echo "Relayer Index: $RLY_INDEX"

              apk add curl jq nodejs npm bash

              if [ -z "$MNEMONIC" ]; then
                MNEMONIC=$(jq -r ".relayers[0].mnemonic" $KEYS_CONFIG)
              fi

              cd /root
              cp /contracts/* .
              npm ci

              echo "Adding chains"
              IBC_CORE_ADDRESS=$(jq -r '.sc_address' /root/altair.json)
              ABI=$(cat /root/abi.json)

              echo "Adding polymer chain"
              POLYMER_ADDRESS=$(node address.js -m "$MNEMONIC" -p polymer | jq -r ".cosmosAddress")

              # TODO: take DENOM from polymer's config
              echo "Transfer tokens to address $POLYMER_ADDRESS"
              DENOM=token
              bash -e /scripts/transfer_tokens.sh $POLYMER_ADDRESS $DENOM http://polymer-genesis.$NAMESPACE.svc.cluster.local:8000/credit

              /vibc-relayer/vibc-relayer chains add --name polymer \
              --rpc-url http://polymer-genesis.$NAMESPACE.svc.cluster.local:26657 \
              --gas-price 0.0stake \
              --account "$POLYMER_ADDRESS" --key "$MNEMONIC" --type cosmos

              echo "Adding ethereum chain"
              ETH_ADDRESS=$(node address.js -m "$MNEMONIC" | jq -r ".ethereumAddress")
              ETH_PRIV_KEY=$(node address.js -m "$MNEMONIC" | jq -r ".ethereumPrivateKey")
              echo "Ethereum address: $ETH_ADDRESS"
              echo "Ethereum private key: $ETH_PRIV_KEY"

              /vibc-relayer/vibc-relayer chains add --name ethereum \
              --rpc-url http://prysm.$NAMESPACE.svc.cluster.local:8545 \
              --gas-price 0.0stake \
              --account "$ETH_ADDRESS" --key "$ETH_PRIV_KEY" --type evm \
              --contract-addr "$IBC_CORE_ADDRESS" \
              --contract-abi "$ABI"

              echo "Setting polling idle time"
              /vibc-relayer/vibc-relayer config set global.polling-idle-time 5000

              echo "Adding paths"
              /vibc-relayer/vibc-relayer paths add polymer ethereum polymer-ethereum || true

              echo "Adding connections"
              {{- range $connection := $relayer.connections }}
              /vibc-relayer/vibc-relayer paths update {{ $connection }} --src-connection connection-0
              {{- end }}
          volumeMounts:
            - mountPath: /root
              name: relayer
            - mountPath: /contracts
              name: contracts
            - mountPath: /keys
              name: keys
            - mountPath: /scripts
              name: scripts
          resources: {{- include "devnet.node.resources" ( dict "node" $relayer "context" $ ) | trim | nindent 12 }}
      containers:
        - name: vibc-relayer
          image: {{ $relayer.vibcImage | default $defaultRelayer.vibcImage }}
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - sh
            - "-c"
            - |
              set -e
              RLY_INDEX=${HOSTNAME##*-}
              echo "Relayer Index: $RLY_INDEX"
              /vibc-relayer/vibc-relayer config set global.log-level verbose

              /vibc-relayer/vibc-relayer start
          resources: {{- include "devnet.node.resources" ( dict "node" $relayer "context" $ ) | trim | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          volumeMounts:
            - mountPath: /root
              name: relayer
        - name: eth-relayer
          image: {{ $relayer.image | default $defaultRelayer.image }}
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KEYS_CONFIG
              value: /keys/keys.json
            - name: MNEMONIC
              valueFrom:
                secretKeyRef:
                  optional: true
                  name: eth-relayer
                  key: relayer
          command:
            - sh
            - "-c"
            - |
              set -e
              apk add curl jq bash

              RLY_INDEX=${HOSTNAME##*-}
              echo "Relayer Index: $RLY_INDEX"

              if [ -z "$MNEMONIC" ]; then
                MNEMONIC=$(jq -r ".relayers[0].mnemonic" $KEYS_CONFIG)
              fi

              PRYSM_IP=$(nslookup prysm.$NAMESPACE.svc.cluster.local | awk '/^Address: / { print $2 }')
              PRYSM_IP=$(echo "$PRYSM_IP" | xargs)

              POLYMER_IP=$(nslookup polymer-genesis.$NAMESPACE.svc.cluster.local | awk '/^Address: / { print $2 }')
              POLYMER_IP=$(echo "$POLYMER_IP" | xargs)

              IBC_CORE_ADDRESS=$(jq -r '.sc_address' /root/altair.json)

              # Make the curl request and store the JSON response in a variable
              response=$(curl -s "http://polymer-genesis.$NAMESPACE.svc.cluster.local:1317/polyibc/core/v1/clients/altair-0/client_state")
              CLIENT_STATE=$(echo "$response" | jq -r '.client_state')

              # Check if the "client_state" key exists in the JSON response
              if [ "$CLIENT_STATE" != "null" ]; then
                echo "Altair light client exists"
              else
                echo "Altair light client does not exist. Creating one..."

                /relayer/eth-relayer --consensus-host "http://prysm.$NAMESPACE.svc.cluster.local:3500" \
                --consensus-grpc-host "prysm.$NAMESPACE.svc.cluster.local:4000" \
                --execution-host "http://prysm.$NAMESPACE.svc.cluster.local:8545" \
                --ibc-core-address "$IBC_CORE_ADDRESS" \
                --ibc-core-abi /root/abi.json \
                --router-host "http://polymer-genesis.$NAMESPACE.svc.cluster.local:9090" \
                --polymer-rpc-addr "http://polymer-genesis.$NAMESPACE.svc.cluster.local:26657" \
                --polymer-account-mnemonic "$MNEMONIC" \
                --create-client-mode --{{$relayer.network}}
              fi

              /relayer/eth-relayer --consensus-host "http://prysm.$NAMESPACE.svc.cluster.local:3500" \
              --consensus-grpc-host "prysm.$NAMESPACE.svc.cluster.local:4000" \
              --execution-host "http://prysm.$NAMESPACE.svc.cluster.local:8545" \
              --ibc-core-address "$IBC_CORE_ADDRESS" \
              --ibc-core-abi /root/abi.json \
              --router-host "http://polymer-genesis.$NAMESPACE.svc.cluster.local:9090" \
              --polymer-rpc-addr "http://$POLYMER_IP:26657" \
              --polymer-account-mnemonic "$MNEMONIC" \
              --{{$relayer.network}}

          resources: {{- include "devnet.node.resources" ( dict "node" $relayer "context" $ ) | trim | nindent 12 }}
          volumeMounts:
            - mountPath: /root
              name: relayer
            - mountPath: /keys
              name: keys
      volumes:
        - name: keys
          configMap:
            name: keys
        - name: scripts
          configMap:
            name: setup-scripts
        - name: contracts
          configMap:
            name: contracts
  volumeClaimTemplates:
    - metadata:
        name: relayer
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi
---
{{- end }}
{{- end }}
