{{- range $chain := .Values.chains }}
{{- if ne $chain.type "virtual" }}
{{ $dataExposer := dict "chain" $chain.name "port" ($.Values.exposer.ports.rest | quote | default "8081") }}
{{ $defaultFile := $.Files.Get "defaults.yaml" | fromYaml }}
{{ $defaultChain := get $defaultFile.defaultChains $chain.type | default dict }}

# merge defaultChain values into the $chain dict
{{ $chain = merge $chain $defaultChain }}

{{- $upgrade := $chain.upgrade | default (dict "enabled" false) }}
{{- $build := .build | default (dict "enabled" false) -}}
{{- $toBuild := or $build.enabled $upgrade.enabled }}

# read faucet from chain values and merge with default faucet values
{{ $faucet := get $chain "faucet" | default dict }}
{{ $faucet = merge $faucet $.Values.faucet }}

{{ $image := $chain.image }}
{{- if $toBuild }}
{{ $image = "anmol1696/runner:latest" }}
{{- end }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $chain.name }}-genesis
spec:
  serviceName: {{ $chain.name }}-genesis
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $chain.type }}
      app.kubernetes.io/name: {{ $chain.name }}-genesis
  template:
    metadata:
      annotations:
        quality: release
        role: api-gateway
        sla: high
        tier: gateway
      labels:
        app.kubernetes.io/instance: {{ $chain.type }}
        app.kubernetes.io/type: {{ $chain.name }}
        app.kubernetes.io/name: {{ $chain.name }}-genesis
        app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    spec:
      {{- include "imagePullSecrets" $chain | indent 6 }}
      initContainers:
        {{- if $toBuild }}
        - name: init-build-images
          image: anmol1696/builder:latest
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - "-c"
            - |
              # Install cosmovisor
              go install github.com/cosmos/cosmos-sdk/cosmovisor/cmd/cosmovisor@v1.0.0

              # Build genesis
              {{- if $upgrade.enabled  }}
              UPGRADE_NAME=genesis CODE_TAG={{ $chain.upgrade.genesis }} bash -e /scripts/build_chain.sh
              {{- range $upgrade := $chain.upgrade.upgrades }}
              UPGRADE_NAME={{ $upgrade.name }} CODE_TAG={{ $upgrade.version }} bash -e /scripts/build_chain.sh
              {{- end }}
              {{- else if $build.enabled }}
              UPGRADE_NAME=genesis CODE_TAG={{ $chain.build.source }} bash -e /scripts/build_chain.sh
              {{- end }}
          env:
            - name: CODE_REF
              value: {{ $chain.repo }}
            - name: UPGRADE_DIR
              value: {{ $chain.home }}/cosmovisor
            - name: GOBIN
              value: /go/bin
            - name: CHAIN_NAME
              value: {{ $chain.name }}
            {{ include "devnet.defaultEvnVars" $chain | indent 12 }}
          resources: {{- include "devnet.node.resources" ( dict "node" $chain "context" $ ) | trim | nindent 12 }}
          volumeMounts:
            - mountPath: {{ $chain.home }}
              name: node
            - mountPath: /configs
              name: addresses
            - mountPath: /scripts
              name: scripts
        {{- end }}
        - name: init-genesis
          image: {{ $image }}
          imagePullPolicy: Always
          env:
            {{- include "devnet.defaultEvnVars" $chain | indent 12 }}
            {{- include "devnet.evnVars" $chain | indent 12 }}
            {{- include "devnet.timeoutVars" $.Values | indent 12 }}
            - name: KEYS_CONFIG
              value: /configs/keys.json
          command:
            - bash
            - "-c"
            - |
              VAL_INDEX=${HOSTNAME##*-}
              echo "Validator Index: $VAL_INDEX"
              {{- if $toBuild }}
              cp $CHAIN_DIR/cosmovisor/genesis/bin/$CHAIN_BIN /usr/bin
              {{- end }}

              if [ -f $CHAIN_DIR/config/genesis.json ]; then
                echo "Genesis file exists, exiting init container"
                exit 0
              fi

              echo "Running setup and config files..."
              bash -e /scripts/setup_genesis.sh
              bash -e /scripts/setup_config.sh
          resources: {{- include "devnet.node.resources" ( dict "node" $chain "context" $ ) | trim | nindent 12 }}
          volumeMounts:
            - mountPath: {{ $chain.home }}
              name: node
            - mountPath: /configs
              name: addresses
            - mountPath: /scripts
              name: scripts
      containers:
        - name: validator
          image: {{ $image }}
          imagePullPolicy: Always
          env:
            {{- include "devnet.defaultEvnVars" $chain | indent 12 }}
            {{- include "devnet.evnVars" $chain | indent 12 }}
            - name: COLLECTOR_SERVICE
              value: collector
            - name: COLLECTOR_PORT
              value: "8070"
          command:
            - bash
            - "-c"
            - |
              {{- if $toBuild }}
              /usr/bin/cosmovisor start
              {{- else }}
              $CHAIN_BIN start
              {{- end }}
          resources: {{- include "devnet.node.resources" ( dict "node" $chain "context" $ ) | trim | nindent 12 }}
          volumeMounts:
            - mountPath: {{ $chain.home }}
              name: node
            - mountPath: /configs
              name: addresses
            - mountPath: /scripts
              name: scripts
          {{- if $.Values.collector.enabled }}
          lifecycle:
            preStop:
              exec:
                command:
                  - bash
                  - "-c"
                  - "-e"
                  - |
                    VAL_INDEX=${HOSTNAME##*-}
                    VAL_NAME=$(jq -r ".genesis[$VAL_INDEX].name" /configs/keys.json)
                    echo "Validator Index: $VAL_INDEX, Key name: $VAL_NAME"

                    COLLECTOR_HOST=http://$COLLECTOR_SERVICE.$NAMESPACE.svc.cluster.local:$COLLECTOR_PORT
                    VAL_NAME=$VAL_NAME COLLECTOR_HOST=$COLLECTOR_HOST bash -e /scripts/register_snapshots.sh
          {{- end }}
        - name: exposer
          image: {{ $.Values.exposer.image }}
          imagePullPolicy: Always
          env:
            {{- include "devnet.genesisVars" $dataExposer | indent 12}}
            - name: EXPOSER_HTTP_PORT
              value: "8081"
            - name: EXPOSER_GRPC_PORT
              value: "9099"
            - name: EXPOSER_GENESIS_FILE
              value: {{ $chain.home }}/config/genesis.json
            - name: EXPOSER_MNEMONIC_FILE
              value: /configs/keys.json
            - name: EXPOSER_PRIV_VAL_FILE
              value: {{ $chain.home }}/config/priv_validator_key.json
          command: [ "/app/exposer/exposer" ]
          resources: {{- include "getResourceObject" $.Values.exposer.resources | trim | nindent 12 }}
          volumeMounts:
            - mountPath: {{ $chain.home }}
              name: node
            - mountPath: /configs
              name: addresses
        - name: faucet
          image: {{ $faucet.image }}
          imagePullPolicy: Always
          env:
            - name: FAUCET_CONCURRENCY
              value: "{{ $faucet.concurrency }}"
            - name: FAUCET_PORT
              value: "{{ $faucet.ports.rest }}"
            - name: FAUCET_MEMO
              value: "faucet txn"
            - name: FAUCET_GAS_PRICE
              value: "0.025{{ $chain.denom }}"
            - name: FAUCET_GAS_LIMIT
              value: "2000000"
            - name: FAUCET_ADDRESS_PREFIX
              value: "{{ $chain.prefix }}"
            - name: FAUCET_REFILL_FACTOR
              value: "8"
            - name: FAUCET_REFILL_THRESHOLD
              value: "20"
            - name: FAUCET_COOLDOWN_TIME
              value: "0"
            - name: COINS
              value: "{{ $chain.coins }}"
            - name: HD_PATH
              value: "{{ $chain.hdPath }}"
          command:
            - bash
            - "-c"
            - |
              export FAUCET_TOKENS=$(printf '%s\n' ${COINS//[[:digit:]]/})

              for coin in ${COINS//,/ }
              do
                  var="FAUCET_CREDIT_AMOUNT_$(printf '%s\n' ${coin//[[:digit:]]/} | tr '[:lower:]' '[:upper:]')"
                  amt="${coin//[!0-9]/}"
                  export $var=$((amt/10000))
              done

              export FAUCET_PATH_PATTERN="${HD_PATH:0:$((${#HD_PATH}-1))}a"
              export FAUCET_MNEMONIC=$(jq -r ".genesis[0].mnemonic" /configs/keys.json)

              echo "FAUCET_MNEMONIC: $FAUCET_MNEMONIC"
              echo "FAUCET_PATH_PATTERN: $FAUCET_PATH_PATTERN"

              export | grep "FAUCET"
              /app/packages/faucet/bin/cosmos-faucet-dist start "http://localhost:26657"
          volumeMounts:
            - mountPath: /configs
              name: addresses
          resources: {{- include "getResourceObject" $faucet.resources | trim | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /status
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: node
          emptyDir: { }
        - name: addresses
          configMap:
            name: keys
        - name: scripts
          configMap:
            name: setup-scripts
---
{{- end }}
{{- end }}
