name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build-exposer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v4
        with:
          go-version: "1.19"
          check-latest: true

      - name: Build exposer
        run: |
          cd exposer && make build

  build-registry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v4
        with:
          go-version: "1.19"
          check-latest: true

      - name: Build registry
        run: |
          cd registry && make build

  build-faucet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v4
        with:
          go-version: "1.19"
          check-latest: true

      - name: Build faucet
        run: |
          cd faucet && make build
