name: E2E tests

on:
  push:
    branches:
      - main
  # Run every day at 18:00 UTC
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-e2e-tests
  cancel-in-progress: true

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        config-file:
          - "two-chain.yaml"
          - "build-chain.yaml"
          - "multi-validator.yaml"
          - "two-chain-gorelayer.yaml"
          - "simapp.yaml"
      fail-fast: true
      max-parallel: 1

    env:
      CONFIG_FILE: "tests/e2e/configs/${{ matrix.config-file }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run remote e2e test
        id: e2e-test
        uses: ./.github/actions/e2e-test
        with:
          config-file: ${{ env.CONFIG_FILE }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          aws-eks-cluster: ${{ vars.AWS_EKS_CLUSTER }}

      # todo: change this to be post step of the action
      - name: Cleanup cluster
        if: always()
        run: |
          helm delete $DEVNET_NAME --debug --namespace $DEVNET_NAMESPACE --wait || true
          kubectl delete namespace $DEVNET_NAMESPACE --wait=true || true
        shell: bash
        env:
          DEVNET_NAME: ${{ steps.e2e-test.outputs.name }}
          DEVNET_NAMESPACE: ${{ steps.e2e-test.outputs.namespace }}
