name: PR tests

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-pr-tests
  cancel-in-progress: true

jobs:
  pr-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        config-file:
          - "one-chain-custom-scripts.yaml"
          - "one-chain.yaml"
          - "one-custom-chain.yaml"
          - "multi-validator.yaml"
          - "simapp.yaml"
      fail-fast: true
      max-parallel: 3

    env:
      CONFIG_FILE: "tests/e2e/configs/${{ matrix.config-file }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v4
        with:
          go-version: "1.19"
          check-latest: true

      - name: Setup Test infra
        id: starship-action
        uses: cosmology-tech/starship-action@0.2.16
        with:
          values: ${{ env.CONFIG_FILE }}
          port-forward: true
          version: 0.0.0
          chart: ./charts/devnet

      - name: Run tests
        run: |
          cd tests/e2e/ && go test -v ./...
        env:
          TEST_CONFIG_FILE: ${{ env.CONFIG_FILE }}

      # todo: change this to be post step of the action
      - name: Cleanup cluster
        if: always()
        run: |
          helm delete $DEVNET_NAME --debug --namespace $DEVNET_NAMESPACE --wait || true
          kubectl delete namespace $DEVNET_NAMESPACE --wait=true || true
        env:
          DEVNET_NAME: ${{ steps.starship-action.outputs.name }}
          DEVNET_NAMESPACE: ${{ steps.starship-action.outputs.namespace }}
